// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQrPnLMCeMDKR9FvgMY_gNzuKFKQw-Sf4',
    appId: '1:425373195781:web:2bdc0dff008f39f529066c',
    messagingSenderId: '425373195781',
    projectId: 'food-app-99a54',
    authDomain: 'food-app-99a54.firebaseapp.com',
    storageBucket: 'food-app-99a54.firebasestorage.app',
    measurementId: 'G-BN69RC1G65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8tD0XXH0MQ8biCIHQXwt5hZsfbHgL_Ls',
    appId: '1:425373195781:android:e8a6b3ebf4c97ab129066c',
    messagingSenderId: '425373195781',
    projectId: 'food-app-99a54',
    storageBucket: 'food-app-99a54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaDe_gYrU03OJdagGM8RnOD8QaAq2w1Ac',
    appId: '1:425373195781:ios:b70c65bc29a68ce129066c',
    messagingSenderId: '425373195781',
    projectId: 'food-app-99a54',
    storageBucket: 'food-app-99a54.firebasestorage.app',
    iosBundleId: 'com.example.mealsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaDe_gYrU03OJdagGM8RnOD8QaAq2w1Ac',
    appId: '1:425373195781:ios:b70c65bc29a68ce129066c',
    messagingSenderId: '425373195781',
    projectId: 'food-app-99a54',
    storageBucket: 'food-app-99a54.firebasestorage.app',
    iosBundleId: 'com.example.mealsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQrPnLMCeMDKR9FvgMY_gNzuKFKQw-Sf4',
    appId: '1:425373195781:web:1297d68f980cc39129066c',
    messagingSenderId: '425373195781',
    projectId: 'food-app-99a54',
    authDomain: 'food-app-99a54.firebaseapp.com',
    storageBucket: 'food-app-99a54.firebasestorage.app',
    measurementId: 'G-11QPFZ0ET0',
  );
}
