// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEiXVOViZy4zxG8-ZFJnswB0QH4TMMMzo',
    appId: '1:357390568485:web:fbc321dbe32a51255483cc',
    messagingSenderId: '357390568485',
    projectId: 'meals-app-852b0',
    authDomain: 'meals-app-852b0.firebaseapp.com',
    storageBucket: 'meals-app-852b0.firebasestorage.app',
    measurementId: 'G-D952WWYF8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ8uINsMPVGAU5GMsMsegyasvTuVrZdnI',
    appId: '1:357390568485:android:4c2c5d8cc97e613b5483cc',
    messagingSenderId: '357390568485',
    projectId: 'meals-app-852b0',
    storageBucket: 'meals-app-852b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY9I9CvZ3wvfRoCm-TnSOpy9HCL39MnVc',
    appId: '1:357390568485:ios:10986794ffc7a2165483cc',
    messagingSenderId: '357390568485',
    projectId: 'meals-app-852b0',
    storageBucket: 'meals-app-852b0.firebasestorage.app',
    iosBundleId: 'com.example.mealsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY9I9CvZ3wvfRoCm-TnSOpy9HCL39MnVc',
    appId: '1:357390568485:ios:10986794ffc7a2165483cc',
    messagingSenderId: '357390568485',
    projectId: 'meals-app-852b0',
    storageBucket: 'meals-app-852b0.firebasestorage.app',
    iosBundleId: 'com.example.mealsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEiXVOViZy4zxG8-ZFJnswB0QH4TMMMzo',
    appId: '1:357390568485:web:bb36558e085ee8615483cc',
    messagingSenderId: '357390568485',
    projectId: 'meals-app-852b0',
    authDomain: 'meals-app-852b0.firebaseapp.com',
    storageBucket: 'meals-app-852b0.firebasestorage.app',
    measurementId: 'G-T9BBMYSGZ4',
  );
}
